name: "diff"
version: "0.1.0"
usage: "Diff the manifest between helm template and helm get manifest"
description: "Diff the manifest between helm template and helm get manifest"
command: "$HELM_PLUGIN_DIR/bin/diff"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"